# Generated by Django 2.2.7 on 2019-12-02 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Document_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Document_type',
                'verbose_name_plural': 'Document_types',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.BigIntegerField()),
                ('client_name', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('document_number', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
                ('id_document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Document_type')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(blank=True, upload_to='Pictures/Supplies')),
                ('quantity', models.IntegerField()),
                ('size', models.CharField(max_length=20)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Category')),
            ],
            options={
                'verbose_name': 'Supplies',
                'verbose_name_plural': 'Supplies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nickname', models.CharField(max_length=30)),
                ('id_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Invoice')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Orders')),
                ('id_supplies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Supplies')),
            ],
            options={
                'verbose_name': 'Order Details',
                'verbose_name_plural': 'Orders Details',
                'ordering': ['id_orders'],
            },
        ),
    ]
